// Copies the app's calculation engine (the ENGINE-EXTRACT spans in
// index.html) and the methodology text (llms-full.txt) into
// worker/src/engine.generated.js, so the MCP server runs exactly the app's
// engine (intent 055). Run from the repo root after any engine change:
//
//   node tools/mcp/build-engine.mjs
//
// tests/test-mcp-worker.mjs fails if the generated file is out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..', '..');
export const OUTPUT = path.join(here, 'worker', 'src', 'engine.generated.js');
export const EXPORTS = ['CURRENT_YEAR', 'UK_REFERENCE', 'projectJoint', 'planSummary', 'planToEngineArgs', 'applyWhatIf',
  'sensitivityAnalysis', 'householdAtRetirement', 'dbPensionsOf', 'deflate', 'findSupportableDelta', 'computeTaxNotes'];

export function buildEngineSource() {
  const html = readFileSync(path.join(root, 'index.html'), 'utf8');
  const START = '// ENGINE-EXTRACT-START';
  const END = '// ENGINE-EXTRACT-END';
  const spans = [];
  for (let i = html.indexOf(START); i !== -1; i = html.indexOf(START, i + START.length)) {
    const j = html.indexOf(END, i);
    if (j === -1) throw new Error('Unpaired ENGINE-EXTRACT-START in index.html');
    spans.push(html.slice(i + START.length, j));
  }
  if (!spans.length) throw new Error('No ENGINE-EXTRACT spans found in index.html');
  const methodology = readFileSync(path.join(root, 'llms-full.txt'), 'utf8');
  return [
    '// GENERATED by tools/mcp/build-engine.mjs from index.html and llms-full.txt.',
    '// Do not edit by hand: change index.html, then run `node tools/mcp/build-engine.mjs`.',
    '/* eslint-disable */',
    spans.join('\n'),
    `export const METHODOLOGY = ${JSON.stringify(methodology)};`,
    `export { ${EXPORTS.join(', ')} };`,
    ''
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(OUTPUT, buildEngineSource());
  console.log(`Wrote ${path.relative(root, OUTPUT)}`);
}
